name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn verify "-Dcheckstyle.skip=true"
        shell: bash

      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-coverage-report-${{ matrix.os }}
          path: target/site/jacoco/
          retention-days: 7
      - name: Package (build .jar)
        run: mvn package -DskipTests -Dcheckstyle.skip=true
        shell :  bash
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: bank-system-jar-${{ matrix.os }}
          path: target/*.jar
          retention-days: 7